version: "3.7"

services:

  db:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: cloud_storage


  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: shumov_cloud
    ports:
      - "8081:8081"
    links:
      - db
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/cloud_storage

  front:
    build:
      context: netology-diplom-frontend
      dockerfile: Dockerfile
    container_name: cloud_frontend
    ports:
      - 8080:8080

